public class Main {
    public static void main(String[] args) {
        int result = new Solution().KSubstring("UBHMeVuUylWcnXWgbDsEdsNgGpUkABFweoIkJeEHrDLeaJnBNHiSzXyiMSSMvzlZnVmwAqfrtTywclZpsHjTfhBTbTIWutYhOKFqcliWEgSItraNbJgirKBSFlRAeRhVbnLDAVBgdvoWPOLqAUATeBNjnejtvtqyICeIzfQdDEbSvnkXjkqNNDwcKIyhdoglqmVqRlvURWOolyLUKBJYFGArqyYTPEEhqZXkmugDtvseVDbghkgmSIdIjdDyijfAkfMWZtauQuZNxcVeMBsfmxPVbTvleClPhaljTndLheYHGulvXGalDRGGMdTrgFipHTYajeNQklXTHlOHrQsWhbFuEYNkFvaMqaOZgbStNpMwCaDVqYsXzZtDxiQfdSrwUGVdJnWyFivHIadyyxxZyTFvBxCHPuDLcYoloKMtUjccJhCkGclEvqcYnefeAiqcjeqzReUlNwqWGsiMwURrmVsazXEAiWEtdWsuAMHNIxMqqWDmqwGdRyfsxLUfiZYLXQhYcoNNmBDEYiSOGYTXyasYmMDUNEHlwolBcyqOAVuYENOKNKKMkCkWqPSEvZpUpaVSAnIcIDcoQTbddlRNPdMFVeJQgakVchPFwAhFDmVvFwAiJSXYXjGsOrlWuxTWfjbDjlkOXGlcelKofhoDtuXHOIFIGYeNjiQuTBkqjVuNHEBONStGoRpCZWKHvRUGzNBuqlMZjGOqKsEzKaiyrXdsWnARgwzHlcBbqNcZTrrFjXhtxPToOwJk",5);

        System.out.println(result);
    }
}
